baseURL = 'https://llhisme.github.io/programming-blog/'
languageCode = 'vi-VN'
defaultContentLanguage = 'vi'
title = 'Blog Lập Trình Mạng'
theme = 'blowfish'

# Enable emoji support
enableEmoji = true

[params]
  colorScheme = "Ocean"
  defaultAppearance = "light" # valid options: light or dark
  autoSwitchAppearance = true

  enableSearch = true
  enableCodeCopy = true
  
  # Custom CSS and JS
  customCSS = ["css/custom.css"]
  customJS = ["js/recent-posts.js"]
  
  robots = ""
  fingerprintAlgorithm = "sha256"
  
  # Background image for homepage - using theme's built-in background
  defaultBackgroundImage = "img/kushin.jpg"

  [params.homepage]
    layout = "background" # valid options: page, profile, hero, card, background, custom
    #homepageImage = "IMAGE.jpg" # used in: hero, and card
    showRecent = true
    showRecentItems = 5
    showMoreLink = true
    showMoreLinkDest = "/posts"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = true # only used when layout equals background
  [params.header]
    layout = "fixed-fill-blur" # valid options: basic, page, fixed, fixed-fill, fixed-fill-blur

  [params.footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.article]
    showDate = true
    showViews = false
    showLikes = false
    showDateUpdated = false
    showAuthor = true
    showHero = true
    heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
    layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
    showBreadcrumbs = false
    showDraftLabel = true
    showEdit = true
    editURL = "https://github.com/llhisme/persional_blog/blob/master/content/"
    editAppendPath = true
    seriesOpened = false
    showHeadingAnchors = true
    showPagination = true
    invertPagination = true
    showReadingTime = false
    showTableOfContents = true
    # showRelatedContent = false
    # relatedContentLimit = 3
    showTaxonomies = true
    showAuthorsBadges = false
    showWordCount = false
    # sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]

  [params.list]
    showHero = true
    heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
    layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
    showBreadcrumbs = false
    showSummary = false
    showViews = false
    showLikes = false
    showTableOfContents = false
    showCards = true
    groupByYear = true
    cardView = true
    cardViewScreenWidth = false
    constrainItemsWidth = false
    orderByWeight = true

  [params.sitemap]
    excludedKinds = ["taxonomy", "term"]

  [params.taxonomy]
    showTermCount = true
    showHero = true
    heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
    layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = false
    showCards = true
    cardView = false

  [params.term]
    showHero = true
    heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
    layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    groupByYear = false
    showCards = true
    cardView = false

  [params.fathomAnalytics]
    # site = "ABC12345"
    # domain = "llama.yoursite.com"

  [params.buymeacoffee]
    # identifier = ""
    # globalWidget = true
    # globalWidgetMessage = "Hello"
    # globalWidgetColor = "#FFDD00"
    # globalWidgetPosition = "Right"

  [params.verification]
    # google = ""
    # bing = ""
    # pinterest = ""
    # yandex = ""

[languages]
  [languages.vi]
    languageCode = "vi-VN"
    languageName = "Tiếng Việt"
    displayName = "VI"
    isoCode = "vi"
    weight = 1
    rtl = false

    title = "llhisme's Blog"
    # logo = "img/logo.png"
    # secondaryLogo = "img/secondary-logo.png"
    description = "Blog cá nhân chia sẻ kiến thức về lập trình Java và JavaScript"
    # copyright = "Copy, _right?_ :thinking_face:"

    dateFormat = "02-01-2006"

    [languages.vi.params]
      displayName = "VI"
      isoCode = "vi"
      rtl = false
      dateFormat = "02-01-2006"
      # logo = "img/logo.png"
      # secondaryLogo = "img/secondary-logo.png"
      # description = ""
      # copyright = "Copy, _right?_ :thinking_face:"

    [languages.vi.author]
      name = "Tên của bạn"
      image = "img/blowfish_logo.png"
      headline = "Lập trình viên Java & JavaScript"
      bio = "Chào mừng đến với blog của tôi! Tôi chia sẻ kiến thức về lập trình Java và JavaScript dành cho người mới bắt đầu."
      links = [
        { email = "mailto:lamlyhao453@gmail.com" },
        { github = "https://github.com/llhisme" },
        { facebook = "https://www.facebook.com/ly.hao.268139" },
      ]

[author]
  name = "Lâm Lý Hào"
  image = "img/blowfish_logo.png"
  headline = "Lập trình viên Java & JavaScript"
  bio = "Chào mừng đến với blog của tôi! Tôi chia sẻ kiến thức về lập trình Java và JavaScript dành cho người mới bắt đầu."
  links = [
    { email = "mailto:lamlyhao453@gmail.com" },
    { github = "https://github.com/llhisme" },
    { facebook = "https://www.facebook.com/ly.hao.268139" },
  ]

[[menus.main]]
  name = "Trang chủ"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Bài viết"
  pageRef = "/posts"
  weight = 20

[[menus.main]]
  name = "Java"
  pageRef = "/categories/java"
  parent = "Bài viết"
  weight = 21

[[menus.main]]
  name = "JavaScript"
  pageRef = "/categories/javascript"
  parent = "Bài viết"
  weight = 22

[[menus.main]]
  name = "Giới thiệu"
  pageRef = "/about"
  weight = 50

[[menus.main]]
  name = "Liên hệ"
  pageRef = "/contact"
  weight = 60

[[menus.footer]]
  name = "Bài viết"
  pageRef = "/posts"
  weight = 10

[[menus.footer]]
  name = "Danh mục"
  pageRef = "/categories"
  weight = 20

[[menus.footer]]
  name = "Thẻ"
  pageRef = "/tags"
  weight = 30

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
